*/ -}}
{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "hdfs.fullname" . }}
  labels:
    {{ include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ required "Ingress path required, please set: .Values.ingress.pathPrefix" .Values.ingress.pathPrefix }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "hdfs.fullname" . }}-namenodes
            port: 
              number: {{ .Values.namenode.ports.http }}
{{- else }}
        backend:
          serviceName: {{ template "hdfs.fullname" . }}-namenodes
          servicePort: {{ .Values.namenode.ports.http }}
{{- end }}

{{- if ne .Values.ingress.host "" }}
    host: {{ .Values.ingress.host }}
{{- end }}
{{- end }}
