*/ -}}
{{- if and .Values.config.rackAwareness .Values.config.rackAwareness.nodeTopologyLabel (not .Values.config.rackAwareness.serviceAccountName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hdfs.namenodeServiceAccountName" . }}
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
{{- end -}}
