*/ -}}
{{- if and .Values.config.rackAwareness .Values.config.rackAwareness.nodeTopologyLabel -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "hdfs.fullname" . }}-namenode
subjects:
- kind: ServiceAccount
  name: {{ template "hdfs.namenodeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "hdfs.fullname" . }}-namenode
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: namenode
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "hdfs.fullname" . }}-namenode
subjects:
- kind: ServiceAccount
  name: {{ template "hdfs.namenodeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
