apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hdfs.fullname" . }}
  labels:
{{ include "hdfs.labels" . | indent 4 }}
data:
{{- range $fileName, $secret := .Values.secrets.files }}
  {{ $fileName }}: {{ $secret | b64enc | quote }}
{{- end }}
